[package]
name = "erc721_stark"
version = "0.1.0"
edition = "2024_07"

[dependencies]
openzeppelin_access = "1.0.0"
openzeppelin_introspection = "1.0.0"
openzeppelin_token = "1.0.0"
starknet = "2.11.4"

[dev-dependencies]
snforge_std = "0.41.0"
assert_macros = "2.11.4"
openzeppelin_testing = "3.0.0"

# TARGET 1: Your main ERC721 contract
[[target.starknet-contract]]
sierra = true
casm = false


[scripts]
test = "snforge test"

[tool.scarb]
allow-prebuilt-plugins = ["snforge_std"]

[tool.fmt]
sort-module-level-items = true
# This part added for coverage report generating.(lcov file)
[profile.dev.cairo]
unstable-add-statements-functions-debug-info = true
unstable-add-statements-code-locations-debug-info = true
inlining-strategy = "avoid"